spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:vanesa}
    password: ${MYSQL_PASSWORD:v.H.i.2006}
    url: jdbc:mysql://roboworld.mysql.database.azure.com:3306/roboworld?createDatabaseIfNotExist=true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never


  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
  #  main:
  #    allow-circular-references: true
  messages:
    basename: lang/messages
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE
    root: info
mail:
  roboworld: "roboworld@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USER:softuni}
  password: ${MAIL_PASSWORD:softuni}


management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

roboworld:
  default.admin.pass: ${DEFAULT_ADMIN_PASS:topsecret}
  remember.me.key: ${REMEMBER_ME_KEY:topsecret}
